org "full"		# organization name for reports
labelstr "^full[-0-9]*"	# label constraint regex: all tapes must match

infofile "/var/lib/amanda/full/curinfo"      # database DIRECTORY
logdir   "/var/lib/amanda/full/logs"         # log directory
indexdir "/var/lib/amanda/full/index"        # index directory

tapetype lto7


mailer "/usr/local/bin/mailxbk"
mailto "brian.kahn@noaa.gov root"
#dumpcycle 1 week	# the number of days in the normal dump cycle
#runspercycle 5          # the number of amdump runs in dumpcycle days
			# (1 week * 5 amdump runs per week -- just weekdays)
#tapecycle 10 tapes	# the number of tapes in rotation
			# 1 week (dumpcycle) times 5 tapes per week (just
			# the weekdays) plus a few to handle errors that
			# need amflush and so we do not overwrite the full
			# backups performed at the beginning of the previous
			# cycle
runtapes 12		# number of tapes to be used in a single run of amdump

define changer my_robot {
  tpchanger "chg-robot:/dev/changer"
  property "tape-device" "0=tape:/dev/nst0"
  device_property "LEOM" "TRUE"
}
tpchanger "my_robot"
amrecover_changer "my_robot"


dtimeout 1800		# number of idle seconds before a dump is aborted.
ctimeout 30		# maximum number of seconds that amcheck waits
			# for each client host
etimeout 30000		# number of seconds per filesystem for estimates.


#includefile "./advanced.conf"


# tapetypes

define tapetype lto6 {
    comment "Created by amtapetype; compression enabled"
    speed 74830 kps
    length 2500 gbytes
    part_size 250 gbytes
    filemark 759 kbytes
    blocksize 32 kbytes
#    part_cache_type memory
#    part_cache_max_size 3G
#    part_cache_dir /backup/holding
}

define tapetype lto7 {
    comment "Created by amtapetype; compression disabled"
    length 6000 gbytes
    part_size 600 gbytes
    filemark 7 kbytes
    speed 82766 kps
    blocksize 32 kbytes
}


define dumptype global {
  comment "Global definitions"
  auth "bsdtcp"
  estimate calcsize
  exclude "./*.sr.lock"
# exclude samba lock files
}

define dumptype gtar {
    global
    program "GNUTAR"
    comment "gtar, no comp, no encr"
    compress none 
    index yes
    priority medium
}

define dumptype gtar-full {
    gtar
    record yes
    strategy noinc
}

define dumptype gtar-incr {
    gtar
    strategy incronly
}

define dumptype gtar-fast {
    gtar
    comment "gtar, fast comp, no encr"
    compress client fast
}


# amcrypt requires aespipe and uuencode
define dumptype encrypt-server {
   gtar
   comment "server symmetric encryption, dumped with tar"
   encrypt server
   server_encrypt "/usr/sbin/amcrypt"
   server_decrypt_option "-d"
}
