[global]
	realm = pmel.noaa.gov
        workgroup = PMEL
        security = domain
        ;security = ads
        ;winbind separator = + 

        server signing = auto
        local master = no
        writable = yes
	; force create mode = 0664
	; force directory mode = 0775

        protocol = SMB2
        ;min protocol = NT1
	;max protocol = SMB2
        log level = 2


[homes]
	comment = Home Directories
        path = /users/%S
	browseable = no
	; force create mode = 0640
	; force directory mode = 0750

[users]
	comment = other peoples homes
        path = /users
        ;valid users = @users

[data]
	comment = All acoustic data
	path = /data
	;valid users = @%h

